name: build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'Building...'
        uses: reuixiy/hugo-deploy@v1 
        # .github/workflows/build.yml
        env: ##Pay attention to code indentation below
          DEPLOY_REPO: PanZiwei/PanZiwei.github.io  # The deploy repo location for object code, not the source code
          DEPLOY_BRANCH: master  
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} # The secret key name in repo
          # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
          TZ: America/New_York
